add 0~9
thecoding2025/abcproject pull request #4
Opened 2023-03-01 17:19 UTC by snows2001

작성 완료 하였습니다. 검토 바랍니다.

2023-03-01 17:31 UTC, thecoding2025 approved these changes
잘했어요.

2023-03-01 18:24 UTC, lim-mi-young commented on num.txt
> +0l23456789
숫자 1이 좀 이상합니다.

2023-03-01 18:37 UTC, lim-mi-young commented on num.txt
> +0l23456789
숫자 1이 좀 이상합니다.

2023-03-01 18:37 UTC, lim-mi-young requested changes
아무래도 알파벳 소문자 엘인것 같습니다.

2023-03-01 20:05 UTC, lim-mi-young approved these changes
작성된 잘된 거 같네요.

2023-03-02 13:02 UTC, merged

2023-03-02 13:10 UTC, snows2001 commented
리뷰 감사합니다.